// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUg-36pYTiYj13YcRWBOeDaqj6SrVCa5Q',
    appId: '1:99418904117:android:94cbcd40d69c42070a437c',
    messagingSenderId: '99418904117',
    projectId: 'bible-38300',
    storageBucket: 'bible-38300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC19d3OE-TGSRfSsc6l7ms_SxZMReQYFcs',
    appId: '1:99418904117:ios:d785e9558b9c9f1d0a437c',
    messagingSenderId: '99418904117',
    projectId: 'bible-38300',
    storageBucket: 'bible-38300.appspot.com',
    androidClientId: '99418904117-4jj0hmqim60ujlqkndhbdrvae8j8olhm.apps.googleusercontent.com',
    iosClientId: '99418904117-l5rm3mhfvtu2cp8j4rjdvoivnu2hup04.apps.googleusercontent.com',
    iosBundleId: 'com.test.vasu',
  );
}
